{% set version = "1.8.0" %}

package:
  name: plant-seg
  version: {{ version }}

source:
  url: https://github.com/hci-unihd/plant-seg/archive/refs/tags/{{ version }}.tar.gz
  sha256: f295c26a852e1fee792056386c0fdc3343d935db15e9c74728c54e38e8748196

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-cache-dir
  number: 0
  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  host:
    - python >=3.9
    - pip

  run:
    - python >=3.9
    - h5py
    - zarr
    - requests
    - pyyaml
    - scikit-image
    - tifffile
    - vigra
    - python-elf
    - napari
    - pyqt
    - python-graphviz
  run_constrained:
    - pytorch >=1.7.0

test:
  imports:
    - plantseg
    - plantseg.legacy_gui
    - plantseg.segmentation

about:
  home: https://github.com/hci-unihd/plant-seg
  summary: 'Cell instance segmentation in densely packed 3D volumetric images'
  description: |
    PlantSeg is a tool for cell instance aware segmentation in densely packed 3D volumetric images. 
    The pipeline uses a two stage segmentation strategy (Neural Network + Graph Partitioning). 
    The pipeline is tuned for plant cell tissue acquired with confocal and light sheet microscopy. 
    Pre-trained models are provided.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hci-unihd.github.io/plant-seg
  dev_url: https://github.com/hci-unihd/plant-seg

extra:
  recipe-maintainers:
    - lorenzocerrone
    - wolny
    - qin-yu
